name: Branch build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - name: Format the entire source tree
        run: nix fmt
      - name: Lint with clj-kondo
        run: nix develop --command clojure -M:clj-kondo --lint src test
      - name: Run tests
        run: nix develop --command clojure -X:dev:test
      - name: Build uberjar
        run: nix develop --command clojure -T:build uber
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/coverage
        id: coverage
        with:
          fail_on_negative_difference: true
          only_list_changed_files: true
      - name: Comment coverage summary on PR
        uses: marocchino/sticky-pull-request-comment@v3
        if: steps.coverage.outputs.file != '' && github.event_name == 'pull_request' && (success() || failure())
        with:
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          path: code-coverage-results.md
